#include <iostream>

#include "ClapTrap.hpp"

int main() {
	ClapTrap trap1("bob", 10, 10, 1);
	trap1.attack("sara");
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.beRepaired(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	trap1.takeDamage(1);
	std::cout << trap1 << '\n';
	return 0;
}
